version: "3.9"

services:
  backend:
    build: .
    container_name: gemini-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: gemini-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: gemini-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
